### ISSUE TITLE
不能上网

### ISSUE THREAD

**Issue by helang0616** [ygcaicn/ss-heroku#1]
那三个网页都是和你说的一样，但连接后就是上不了网

**Comment by ygcaicn** [comment]
还有bug

可以先用v2ray:

https://github.com/ygcaicn/v2ray-heroku-undone

**Comment by helang0616** [comment]
> 还有bug
> 
> 可以先用v2ray:
> 
> https://github.com/ygcaicn/v2ray-heroku-undone

**Comment by helang0616** [comment]
只能映射到443端口吗，改成其他可不可以。

**Comment by ygcaicn** [comment]
不可以，这是由Heroku控制，由Heroku做路由，你的应用只能跑在他给你随机分配的$PORT端口，然后heroku根据访问的app名称转发到给你分配的端口。

**Comment by ygcaicn** [comment]
已解决。
