### ISSUE TITLE
部署后 ， /qr_img   /qr_ing/v2.png都是404

### ISSUE THREAD

**Issue by hulao6** [ygcaicn/ss-heroku#3]
部署后 ，域名可以访问   /qr_img   /qr_ing/v2.png都是404

请问 ， 这怎么解决呀？ 

gui-config.json

`{
  "version": "4.1.9.2",
  "configs": [
    {
      "server": "kinganmi-ss.herokuapp.com",
      "server_port": 443,
      "password": "2b976bca-66fe-405f-aaf8-111111111",
      "method": "rc4-md5",
      "plugin": "",
      "plugin_opts": "",
      "plugin_args": "",
      "remarks": "",
      "timeout": 5
    }]`

**Comment by ygcaicn** [comment]
是否更改了QR_Path呢？

**Comment by hulao6** [comment]
> 是否更改了QR_Path呢？

没有改
