### ISSUE TITLE
最新版已修复，当前可用！

### ISSUE THREAD

**Issue by ygcaicn** [ygcaicn/ss-heroku#6]
由于Caddy版本升级，以前部署的均无法使用，需要重新部署。

**Comment by playnetcn** [comment]
OK

**Comment by silencebbb** [comment]
重新部署好像也不行

**Comment by ygcaicn** [comment]
> 重新部署好像也不行

具体点呢？

**Comment by silencebbb** [comment]
我截图了，但是这里无法上传图片 。

**Comment by ygcaicn** [comment]
> 我截图了，但是这里无法上传图片 。

可以上传的，评论框直接粘贴即可

**Comment by silencebbb** [comment]
https://send.firefox.com/download/7c811fb28046569a/#fkFKH2RffDxW0s9vHGR9Bw

我传网盘了。

**Comment by silencebbb** [comment]
![1](https://user-images.githubusercontent.com/26780624/81251678-6daf1780-9056-11ea-8462-5a68199b5010.jpg)
![2](https://user-images.githubusercontent.com/26780624/81251682-6f78db00-9056-11ea-9895-841bfc5bda2e.jpg)

**Comment by silencebbb** [comment]
哈哈 我好笨。

**Comment by ygcaicn** [comment]
你使用了自己的域名吗？

**Comment by silencebbb** [comment]
用了自己的域名稍等我重新部署下。给你添麻烦了。。。

**Comment by ygcaicn** [comment]
> 用了自己的域名稍等我重新部署下。给你添麻烦了。。。

重新部署先测试自带域名是否正常。另外目前欧洲节点速度较快。

**Comment by silencebbb** [comment]
我就是觉得不稳定挂的CDN 您是直接访问吗？

**Comment by ygcaicn** [comment]
> 我就是觉得不稳定挂的CDN 您是直接访问吗？

是直接访问

**Comment by silencebbb** [comment]
好的我 测试下欧洲的， 就是挂CDN后不能访问了。好奇怪原来可以。

**Comment by ygcaicn** [comment]
> 好的我 测试下欧洲的， 就是挂CDN后不能访问了。好奇怪原来可以。

你也可以切换Branch，继续使用caddy部署试试

**Comment by silencebbb** [comment]
vmess/encoding: failed to read response header  这个报错 是不是服务端的时间没有校准？

**Comment by ygcaicn** [comment]
> vmess/encoding: failed to read response header 这个报错 是不是服务端的时间没有校准？

Heroku页面->More->Run Console->输入：date 查看服务器时间

**Comment by silencebbb** [comment]
![image](https://user-images.githubusercontent.com/26780624/81256079-f5e6ea00-9061-11ea-85d0-cb001d223d31.png)
欧洲和美国服务器重新都部署了2次  网站可以访问域名PING不通。s输入path后 显示 404错误

![image](https://user-images.githubusercontent.com/26780624/81256127-24fd5b80-9062-11ea-8b2f-f1f4b5454cdb.png)

**Comment by silencebbb** [comment]
![image](https://user-images.githubusercontent.com/26780624/81256225-64c44300-9062-11ea-9382-8d27278a1174.png)

**Comment by silencebbb** [comment]
果然是时间闹得鬼  时间跟本地时间不对应。。。

**Comment by silencebbb** [comment]
脚本没有更改服务器时间  V2需要服务器跟本地时间同步。

**Comment by ygcaicn** [comment]
> 果然是时间闹得鬼 时间跟本地时间不对应。。。

我看你时间没有问题啊，时区差异不影响，是不是你本地时间错了。

ping不通正常，heroapp开启了icmp防火墙

**Comment by silencebbb** [comment]
我再试试 。。。不知道为啥就不行。我再部署次去。

**Comment by ygcaicn** [comment]
刚刚测试，绑定域名后使用cf加速，ssl必须设置为灵活模式。原因：绑定域名后heroapp不会自动签证书，只提供http服务。

美国的使用cf加速后1080p没问题，欧洲不使用cf比较快。（目前5.07）

![image](https://user-images.githubusercontent.com/17684070/81256657-b15c4e00-9063-11ea-94ad-b5a46b291d19.png)

**Comment by ygcaicn** [comment]
> 我再试试 。。。不知道为啥就不行。我再部署次去。

客户端用的什么？配置邮件给我我给你试试

**Comment by silencebbb** [comment]
![image](https://user-images.githubusercontent.com/26780624/81256955-9211f080-9064-11ea-8cc8-aa637bb62bf0.png)
![image](https://user-images.githubusercontent.com/26780624/81256988-ae159200-9064-11ea-866e-4e026bd1fbd4.png)
原来脚本是可以代理的 我这个为什么输入地址是404呢？

**Comment by silencebbb** [comment]
客户端用的 v2rayN  内核用的最新的。

**Comment by silencebbb** [comment]
![image](https://user-images.githubusercontent.com/26780624/81257090-f92fa500-9064-11ea-85e4-b1567b5a5606.png)

**Comment by ygcaicn** [comment]
> ![image](https://user-images.githubusercontent.com/26780624/81256955-9211f080-9064-11ea-8cc8-aa637bb62bf0.png)
> ![image](https://user-images.githubusercontent.com/26780624/81256988-ae159200-9064-11ea-866e-4e026bd1fbd4.png)
> 原来脚本是可以代理的 我这个为什么输入地址是404呢？

qr_path和v2_path这样有问题，v2path的123会会匹配到qr_path。path修改一下吧。（后期我会考虑更新Nginx配置解决这个问题）

正常访问v2_path应该看到代理网站的404才对。

另外这个部署的是ss+v2ray-plugin用v2rayN客户端可以吗？（我不用windows不清楚）

**Comment by silencebbb** [comment]
ss+v2ray-plugin用v2rayN客户端现在不能使用。用的WINDOWS系统  
qr_path和v2_path

我都不知道应该怎么填写好了。

**Comment by ygcaicn** [comment]
> ss+v2ray-plugin用v2rayN客户端现在不能使用。用的WINDOWS系统
> qr_path和v2_path
> 
> 我都不知道应该怎么填写好了。

qr_path仅用于生成配置二维码，无其它用途。
qr_path默认，v2_path用uuid好了。<http://www.uuid.online/>

**Comment by silencebbb** [comment]
我现在部署试试

**Comment by ygcaicn** [comment]
> 我现在部署试试

直接修改Vars即可。

**Comment by silencebbb** [comment]
还是看不到二维码  404

**Comment by silencebbb** [comment]
![image](https://user-images.githubusercontent.com/26780624/81258198-b58a6a80-9067-11ea-9684-b02cd2d0c4b7.png)
![image](https://user-images.githubusercontent.com/26780624/81258216-be7b3c00-9067-11ea-8965-d54cd43cefde.png)

**Comment by silencebbb** [comment]
![image](https://user-images.githubusercontent.com/26780624/81258295-e9fe2680-9067-11ea-88b8-12a323276d0a.png)
![image](https://user-images.githubusercontent.com/26780624/81258329-fe422380-9067-11ea-899b-a3706c7dc77e.png)

**Comment by ygcaicn** [comment]
> 还是看不到二维码 404

![image](https://user-images.githubusercontent.com/17684070/81258670-c8ea0580-9068-11ea-9fd5-1df865d9fa3a.png)


客户端请使用shadowsocks+v2ray-plugin，另外部署参数都使用默认吧。

**Comment by silencebbb** [comment]
https://cdn001.herokuapp.com/1   您那现在能打开吗？

![image](https://user-images.githubusercontent.com/26780624/81259279-3480a280-906a-11ea-8282-3197e5e5f28a.png)
我这里打不开

**Comment by silencebbb** [comment]
我再开一个全默认参数去试试

**Comment by ygcaicn** [comment]
> https://cdn001.herokuapp.com/1 您那现在能打开吗？
> 
> ![image](https://user-images.githubusercontent.com/26780624/81259279-3480a280-906a-11ea-8282-3197e5e5f28a.png)
> 我这里打不开

https://cdn001.herokuapp.com/1/

https://cdn001.herokuapp.com/1/v2.png

**Comment by silencebbb** [comment]
明白了就是  /1后面还要有个 / 我现在去导入看看能不能用  您也导入测试下

**Comment by ygcaicn** [comment]
> 明白了就是 /1后面还要有个 / 我现在去导入看看能不能用 您也导入测试下

我测试了没问题，客户端用ss+v2ray-plugin


如果要用v2rayNg去这里部署：

<https://github.com/ygcaicn/v2ray-heroku>

**Comment by silencebbb** [comment]
好的我测试下那个，这个我直接用的v2rayNg怎么都没成功，估计客户端问题。真给您添麻烦了。。。

**Comment by silencebbb** [comment]
https://github.com/ygcaicn/v2ray-heroku   没有问题了感谢！

想薅羊毛太不容易了。

感谢耐心解答，从刚开始我就应该用那个部署。

我原来也部署过后来失效了，然后就不知道怎么的就用了SS那个。。。

见谅。

**Comment by jik1818** [comment]
2ray的TLS实现存在被识别风险 

原issue: https://github.com/v2ray/discussion/issues/704

v2ray的TLS实现手动指定了cipher suite，使得其拥有了独特的指纹，可以被精确识别。
