### ISSUE TITLE
v2ray的TLS实现存在被识别风险 

### ISSUE THREAD

**Issue by jik1818** [ygcaicn/ss-heroku#7]
2ray的TLS实现存在被识别风险 

原issue: https://github.com/v2ray/discussion/issues/704

v2ray的TLS实现手动指定了cipher suite，使得其拥有了独特的指纹，可以被精确识别。

**Comment by ygcaicn** [comment]
主要是客户端的问题，大家尽快更新客户端。

<https://github.com/shadowsocks/v2ray-plugin/releases>

<https://github.com/shadowsocks/v2ray-plugin-android/releases>

之前部署的heroku app理论上不受此次issue影响，不放心也可以更新！

更新参考：<https://github.com/ygcaicn/ss-heroku#3-%E6%9B%B4%E6%96%B0>

**Comment by jik1818** [comment]
https://github.com/v2ray/v2ray-core/issues/2542

V2Ray 的开发和发布仓库已经移动至 https://github.com/v2fly/v2ray-core ，请开发者以此仓库的内容为基准，并将PR发布至这里。
