### ISSUE TITLE
关于服务端部署的问题

### ISSUE THREAD

**Issue by playnetcn** [ygcaicn/ss-heroku#8]
服务端部署的时候需要部署shadowsocks-libev和v2ray-plugin，这个项目会经常更新，能否在服务端做一个链接，每次部署就直接取这个项目的最新程序安装版本，这样简化您那还得更新服务端的程序文件。

**Comment by ygcaicn** [comment]
@playnetcn  默认就是安装最新版本的v2ray-plugin，v2ray-plugin仓库更新后，**重启** app即拉取最新版。shadowsocks-libev可以考虑在重启时加入更新。
