### ISSUE TITLE
官网版本已经升级，服务端程序是否需要升级？

### ISSUE THREAD

**Issue by playnetcn** [ygcaicn/ss-heroku#9]
v2ray-plugin版本已经升级到1.3.1
https://github.com/shadowsocks/v2ray-plugin/releases/
v2ray-plugin-android版本已经升级到1.3.3
https://github.com/shadowsocks/v2ray-plugin-android/releases/
ss-heroku服务端程序是否也需要升级一下？

**Comment by ygcaicn** [comment]
v2ray-plugin服务端默认使用最新
![image](https://user-images.githubusercontent.com/17684070/96392259-1e1c6c80-11ee-11eb-8992-f42837611f79.png)
Restart时自动拉取最新。
